import { ResourceDTO } from '@/lib/types';

export const FALLBACK_CATALOG: ResourceDTO[] = [
  {
    id: 'res-101',
    barcode: '005.133 DDIA',
    title: 'Designing Data-Intensive Applications',
    authorOrBrand: 'Martin Kleppmann',
    description: 'The definitive guide to distributed systems, storage engines, consensus protocols, and stream processing architectures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-A1',
    tags: ['distributed-systems', 'architecture', 'databases', 'computer-science'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-102',
    barcode: '005.741 MONGO',
    title: 'MongoDB: The Definitive Guide (3rd Ed)',
    authorOrBrand: 'Shannon Bradshaw & Eoin Brazil',
    description: 'Comprehensive guide to document data modeling, aggregation pipelines, replica sets, and sharded cluster management.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491954249-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 0,
    location: 'SHELF-A2',
    tags: ['database', 'nosql', 'mongodb', 'software-engineering'],
    status: 'BORROWED',
    activeQueueCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-103',
    barcode: '005.276 SPRING',
    title: 'Spring Boot 3 in Action',
    authorOrBrand: 'Craig Walls',
    description: 'Building microservices, Spring Security JWT authentication, WebFlux reactive streams, and REST API controllers.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781617292545-L.jpg',
    type: 'BOOK',
    totalQuantity: 3,
    availableQuantity: 1,
    location: 'SHELF-A3',
    tags: ['java', 'spring-boot', 'backend', 'web-development'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-104',
    barcode: '005.430 OS10',
    title: 'Operating System Concepts (10th Ed)',
    authorOrBrand: 'Abraham Silberschatz & Peter B. Galvin',
    description: 'Process synchronization, virtual memory management, file systems, I/O subsystems, and kernel architecture.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781118063330-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-A4',
    tags: ['operating-systems', 'kernel', 'cs-core'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-105',
    barcode: '005.133 SICP',
    title: 'Structure and Interpretation of Computer Programs',
    authorOrBrand: 'Harold Abelson & Gerald Jay Sussman',
    description: 'Lisp, functional programming, data abstraction, metalinguistic abstraction, and register machine execution.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262510875-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 1,
    location: 'SHELF-A5',
    tags: ['programming-theory', 'lisp', 'cs-classic'],
    status: 'BORROWED',
    activeQueueCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-106',
    barcode: '005.740 DBC',
    title: 'Database System Concepts (7th Ed)',
    authorOrBrand: 'Silberschatz, Korth & Sudarshan',
    description: 'Relational algebra, SQL, query optimization, transaction processing, concurrency control, and index structures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780078022159-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-A6',
    tags: ['databases', 'sql', 'transactions'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-107',
    barcode: '005.117 CLN',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    authorOrBrand: 'Robert C. Martin (Uncle Bob)',
    description: 'Principles, patterns, and practices of writing clean, readable, refactorable, and maintainable software code.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-B1',
    tags: ['clean-code', 'refactoring', 'agile'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-108',
    barcode: '005.300 SYS',
    title: 'System Design Interview — An Insider\'s Guide',
    authorOrBrand: 'Alex Xu',
    description: 'Step-by-step framework for designing large-scale web systems: rate limiters, key-value stores, distributed caches, and newsfeed algorithms.',
    coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71u9i8S2GGL.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 1,
    location: 'SHELF-B2',
    tags: ['system-design', 'interview', 'scalability'],
    status: 'AVAILABLE',
    activeQueueCount: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-109',
    barcode: '005.100 CLRS',
    title: 'Introduction to Algorithms (CLRS 4th Edition)',
    authorOrBrand: 'Thomas H. Cormen, Charles E. Leiserson',
    description: 'The standard algorithm textbook covering dynamic programming, graph algorithms, NP-completeness, and B-trees.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262046305-L.jpg',
    type: 'BOOK',
    totalQuantity: 8,
    availableQuantity: 5,
    location: 'SHELF-B3',
    tags: ['algorithms', 'data-structures', 'cs-theory'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-110',
    barcode: '004.600 NET',
    title: 'Computer Networking: A Top-Down Approach (8th Ed)',
    authorOrBrand: 'James Kurose & Keith Ross',
    description: 'Top-down layer approach to computer networks: HTTP/3, TCP/UDP sockets, BGP routing protocols, and Wi-Fi security.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780133594140-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 2,
    location: 'SHELF-C1',
    tags: ['networking', 'protocols', 'tcp-ip'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-111',
    barcode: '006.300 AIMA',
    title: 'Artificial Intelligence: A Modern Approach (4th Ed)',
    authorOrBrand: 'Stuart Russell & Peter Norvig',
    description: 'The leading textbook in AI covering probabilistic reasoning, search algorithms, reinforcement learning, and NLP.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134610993-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 0,
    location: 'SHELF-C2',
    tags: ['ai', 'machine-learning', 'python'],
    status: 'BORROWED',
    activeQueueCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-112',
    barcode: '006.310 DEEP',
    title: 'Deep Learning (Adaptive Computation & ML Series)',
    authorOrBrand: 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
    description: 'Mathematical foundation of deep neural networks, backpropagation, CNNs, Transformers, and Generative Adversarial Networks.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262035613-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-C3',
    tags: ['deep-learning', 'neural-networks', 'pytorch'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-113',
    barcode: '621.398 RISCV',
    title: 'Computer Organization & Design: RISC-V Edition',
    authorOrBrand: 'David A. Patterson & John L. Hennessy',
    description: 'Hardware/software interface, RISC-V instruction set architecture, pipelined datapath design, and cache memory hierarchy.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780128122754-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'SHELF-C4',
    tags: ['architecture', 'risc-v', 'hardware-design'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-114',
    barcode: '005.100 TAOCP',
    title: 'The Art of Computer Programming (Vol 1-4)',
    authorOrBrand: 'Donald E. Knuth',
    description: 'Fundamental algorithms, information structures, seminumerical algorithms, sorting, searching, and combinatorial algorithms.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321751041-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 4,
    location: 'SHELF-C5',
    tags: ['algorithms', 'knuth', 'cs-classic'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-115',
    barcode: '005.453 DRAGON',
    title: 'Compilers: Principles, Techniques & Tools (Dragon Book)',
    authorOrBrand: 'Aho, Lam, Sethi & Ullman',
    description: 'Lexical analysis, LL/LR parsing, syntax-directed translation, intermediate code generation, and instruction-level optimization.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321486813-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-C6',
    tags: ['compilers', 'parsing', 'programming-languages'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-116',
    barcode: '004.360 DIST',
    title: 'Distributed Systems: Principles and Paradigms',
    authorOrBrand: 'Andrew S. Tanenbaum & Maarten Van Steen',
    description: 'Architectures, processes, communication, naming, synchronization, consistency models, fault tolerance, and security in distributed systems.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781543057386-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-D1',
    tags: ['distributed-systems', 'fault-tolerance', 'consensus'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-117',
    barcode: '005.131 CSAPP',
    title: 'Computer Systems: A Programmer\'s Perspective',
    authorOrBrand: 'Randal E. Bryant & David R. O\'Hallaron',
    description: 'Machine-level code execution, processor architecture, virtual memory, dynamic memory allocation, and concurrent programming.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134092669-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 5,
    location: 'SHELF-D2',
    tags: ['cs-systems', 'c-programming', 'memory'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-118',
    barcode: '006.312 PDS',
    title: 'Python Data Science Handbook (2nd Ed)',
    authorOrBrand: 'Jake VanderPlas',
    description: 'Essential tools for working with data in Python: IPython, NumPy, Pandas, Matplotlib, and Scikit-Learn pipelines.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781098115784-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-D3',
    tags: ['python', 'data-science', 'pandas'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-119',
    barcode: '005.100 DAA',
    title: 'Algorithms Unlocked (MIT Press)',
    authorOrBrand: 'Thomas H. Cormen',
    description: 'Gentle introduction to computer algorithms: searching, sorting, graph algorithms, string processing, and basic cryptography.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262518802-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-D4',
    tags: ['algorithms', 'intro-cs', 'mit-press'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-120',
    barcode: '005.133 HASK',
    title: 'Learn You a Haskell for Great Good!',
    authorOrBrand: 'Miran Lipovača',
    description: 'Fun and accessible introduction to functional programming, purity, immutability, monads, functors, and typeclasses in Haskell.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781593272838-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-D5',
    tags: ['haskell', 'functional-programming', 'types'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-121',
    barcode: '005.740 SQL2',
    title: 'High Performance MySQL (4th Edition)',
    authorOrBrand: 'Silvia Botros & Jeremy Tinley',
    description: 'Optimization, backups, replication, scaling, indexing, InnoDB engine internals, and query execution profiling.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492080519-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-E1',
    tags: ['database', 'mysql', 'sql-tuning'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-122',
    barcode: '006.310 PRML',
    title: 'Pattern Recognition and Machine Learning',
    authorOrBrand: 'Christopher M. Bishop',
    description: 'Comprehensive introduction to Bayesian methods, linear classification, neural networks, kernel methods, and graphical models.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780387310732-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 3,
    location: 'SHELF-E2',
    tags: ['machine-learning', 'statistics', 'bayesian'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-123',
    barcode: '005.133 CPP',
    title: 'The C++ Programming Language (4th Edition)',
    authorOrBrand: 'Bjarne Stroustrup',
    description: 'Definitive resource on C++11 core language features, standard library containers, move semantics, and generic programming.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321563842-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 5,
    location: 'SHELF-E3',
    tags: ['cpp', 'programming', 'stl'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-124',
    barcode: '005.133 RUST',
    title: 'The Rust Programming Language',
    authorOrBrand: 'Steve Klabnik & Carol Nichols',
    description: 'Memory safety without garbage collection: ownership, borrowing, lifetimes, cargo package manager, and concurrency.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781593278281-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-E4',
    tags: ['rust', 'systems-programming', 'memory-safety'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-125',
    barcode: '005.754 REDIS',
    title: 'Redis in Action',
    authorOrBrand: 'Josiah L. Carlson',
    description: 'In-memory data structure store: key-value caching, Pub/Sub messaging, geospatial indexes, Lua scripting, and Sentinel cluster HA.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781617290855-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-E5',
    tags: ['redis', 'caching', 'nosql'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-126',
    barcode: '004.620 KAFKA',
    title: 'Kafka: The Definitive Guide (2nd Edition)',
    authorOrBrand: 'Gwen Shapira, Todd Palino',
    description: 'Distributed event streaming platform: partition architecture, consumer groups, Kafka Connect, Schema Registry, and Exactly-Once Semantics.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492043089-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 3,
    location: 'SHELF-F1',
    tags: ['kafka', 'event-streaming', 'distributed-systems'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-127',
    barcode: '005.800 SEC',
    title: 'The Web Application Hacker\'s Handbook (2nd Ed)',
    authorOrBrand: 'Dafydd Stuttard & Marcus Pinto',
    description: 'Attacking and defending web applications: SQL injection, XSS, CSRF, authentication bypass, session hijacking, and API security.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781118026472-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 2,
    location: 'SHELF-F2',
    tags: ['cybersecurity', 'web-security', 'pentesting'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-128',
    barcode: '006.370 CV',
    title: 'Computer Vision: Algorithms and Applications',
    authorOrBrand: 'Richard Szeliski',
    description: 'Image formation, feature detection, motion estimation, structure from motion, 3D reconstruction, and deep learning vision models.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781848829343-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-F3',
    tags: ['computer-vision', 'opencv', 'image-processing'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-129',
    barcode: '006.380 RL',
    title: 'Reinforcement Learning: An Introduction (2nd Ed)',
    authorOrBrand: 'Richard S. Sutton & Andrew G. Barto',
    description: 'Markov decision processes, dynamic programming, Monte Carlo methods, Temporal-Difference learning, Q-learning, and policy gradients.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262039246-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-F4',
    tags: ['reinforcement-learning', 'ai', 'q-learning'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-130',
    barcode: '005.140 TDD',
    title: 'Test Driven Development: By Example',
    authorOrBrand: 'Kent Beck',
    description: 'Red-Green-Refactor workflow, writing clean automated unit tests, mock objects, and test-driven architecture design patterns.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321146533-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-F5',
    tags: ['tdd', 'testing', 'software-engineering'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-131',
    barcode: '005.730 DS',
    title: 'Data Structures and Algorithm Analysis in C++',
    authorOrBrand: 'Mark Allen Weiss',
    description: 'AVL trees, Splay trees, Priority Queues (Heaps), Disjoint Set data structure, Graph algorithms (Dijkstra, Kruskal), and amortized analysis.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780132847377-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 4,
    location: 'SHELF-G1',
    tags: ['data-structures', 'algorithms', 'cpp'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-132',
    barcode: '004.350 PAR',
    title: 'An Introduction to Parallel Programming',
    authorOrBrand: 'Peter Pacheco',
    description: 'MPI (Message Passing Interface), Pthreads, OpenMP multi-threading, GPU parallel computing, and performance scalability tuning.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780123742605-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-G2',
    tags: ['parallel-computing', 'mpi', 'openmp'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-133',
    barcode: '005.300 K8S',
    title: 'Kubernetes Up & Running (3rd Edition)',
    authorOrBrand: 'Brendan Burns, Joe Beda, Kelsey Hightower',
    description: 'Container orchestration: Pods, Services, Ingress controllers, ConfigMaps, Secrets, Horizontal Pod Autoscaling, and Helm charts.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781098110208-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-G3',
    tags: ['kubernetes', 'devops', 'docker'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-134',
    barcode: '005.133 GO',
    title: 'The Go Programming Language',
    authorOrBrand: 'Alan A. A. Donovan & Brian W. Kernighan',
    description: 'Goroutines, channels, interfaces, reflection, low-level unsafe pointer operations, and building concurrent cloud services in Go.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134190440-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-G4',
    tags: ['golang', 'concurrency', 'cloud-native'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-135',
    barcode: '005.133 PY',
    title: 'Fluent Python (2nd Edition)',
    authorOrBrand: 'Luciano Ramalho',
    description: 'Pythonic data models, generator functions, coroutines, asyncio event loops, type hinting, decorators, and meta-programming.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491946008-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-G5',
    tags: ['python', 'advanced-python', 'asyncio'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-136',
    barcode: '006.310 PYTORCH',
    title: 'Programming PyTorch for Deep Learning',
    authorOrBrand: 'Ian Pointer',
    description: 'Building, training, and deploying neural networks: CNNs, Transfer Learning, Recurrent Networks, TensorBoard, and PyTorch Lightning.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492045359-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 2,
    location: 'SHELF-H1',
    tags: ['pytorch', 'deep-learning', 'ai'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-137',
    barcode: '005.741 CASS',
    title: 'Cassandra: The Definitive Guide (3rd Edition)',
    authorOrBrand: 'Jeff Carpenter & Eben Hewitt',
    description: 'Distributed NoSQL database: peer-to-peer architecture, tuneable consistency levels, CQL, SSTables, and cross-datacenter replication.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492055624-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-H2',
    tags: ['cassandra', 'nosql', 'distributed-database'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-138',
    barcode: '004.220 ARCH',
    title: 'Computer Architecture: A Quantitative Approach (6th Ed)',
    authorOrBrand: 'John L. Hennessy & David A. Patterson',
    description: 'Instruction-level parallelism, speculative execution, cache hierarchies, domain-specific accelerators, and GPU SIMD architectures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780128119051-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-H3',
    tags: ['computer-architecture', 'hardware-theory', 'processors'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-139',
    barcode: '530.12 QUANT',
    title: 'Principles of Quantum Mechanics (2nd Ed)',
    authorOrBrand: 'R. Shankar',
    description: 'Mathematical foundations of quantum mechanics: vector spaces, Dirac notation, harmonic oscillator, spin, and perturbation theory.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780306447908-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'SHELF-H4',
    tags: ['quantum-mechanics', 'physics', 'mathematics'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-140',
    barcode: '512.2 GROUPS',
    title: 'Abstract Algebra (3rd Edition)',
    authorOrBrand: 'David S. Dummit & Richard M. Foote',
    description: 'Group theory, ring theory, Galois theory, module theory, vector spaces, and commutative algebra.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780471433347-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 4,
    location: 'SHELF-H5',
    tags: ['abstract-algebra', 'mathematics', 'group-theory'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-141',
    barcode: '515.35 DEQ',
    title: 'Differential Equations & Linear Algebra (4th Ed)',
    authorOrBrand: 'C. Henry Edwards & David E. Penney',
    description: 'First-order equations, linear systems, eigenvalues, Laplace transforms, Fourier series, and boundary value problems.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134491431-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-I1',
    tags: ['differential-equations', 'linear-algebra', 'math'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-142',
    barcode: '519.5 PROB',
    title: 'Probability & Random Processes for Electrical Engineering',
    authorOrBrand: 'Alberto Leon-Garcia',
    description: 'Probability spaces, random variables, Markov chains, spectral density, stationary processes, and queueing theory.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780201500882-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-I2',
    tags: ['probability', 'stochastic', 'math'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-143',
    barcode: '621.381 CKT',
    title: 'Microelectronic Circuits (8th Edition)',
    authorOrBrand: 'Adel S. Sedra & Kenneth C. Smith',
    description: 'Operational amplifiers, MOSFETs, BJTs, frequency response, feedback amplifiers, and integrated circuit design.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780190853464-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-I3',
    tags: ['circuits', 'electronics', 'engineering'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-144',
    barcode: '621.382 SIG',
    title: 'Signals and Systems (2nd Edition)',
    authorOrBrand: 'Alan V. Oppenheim & Alan S. Willsky',
    description: 'Continuous-time and discrete-time signals, Fourier transforms, Laplace transforms, z-transforms, and linear time-invariant systems.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780138147570-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 5,
    location: 'SHELF-I4',
    tags: ['signals-systems', 'fourier', 'dsp'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-145',
    barcode: '621.389 DSP',
    title: 'Discrete-Time Signal Processing (3rd Edition)',
    authorOrBrand: 'Alan V. Oppenheim & Ronald W. Schafer',
    description: 'Sampling theory, z-transform analysis, FIR/IIR filter design, Fast Fourier Transform (FFT) algorithms, and multirate DSP.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780131988422-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-I5',
    tags: ['dsp', 'signal-processing', 'fft'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-146',
    barcode: '629.8 CTL',
    title: 'Modern Control Engineering (5th Edition)',
    authorOrBrand: 'Katsuhiko Ogata',
    description: 'State-space representation, root locus analysis, Bode plots, Nyquist stability criterion, and PID controller design.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780136156734-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'SHELF-J1',
    tags: ['control-systems', 'robotics', 'engineering'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-147',
    barcode: '511.5 GRAPH',
    title: 'Introduction to Graph Theory (2nd Edition)',
    authorOrBrand: 'Douglas B. West',
    description: 'Trees, matchings, planarity, colorings, Eulerian and Hamiltonian circuits, network flows, and random graphs.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780130144003-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 4,
    location: 'SHELF-J2',
    tags: ['graph-theory', 'discrete-math', 'algorithms'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-148',
    barcode: '512.5 LA',
    title: 'Linear Algebra and Its Applications (6th Edition)',
    authorOrBrand: 'David C. Lay, Steven R. Lay',
    description: 'Matrix algebra, vector spaces, linear transformations, eigenvalues, singular value decomposition (SVD), and least squares.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780135851159-L.jpg',
    type: 'BOOK',
    totalQuantity: 8,
    availableQuantity: 6,
    location: 'SHELF-J3',
    tags: ['linear-algebra', 'matrices', 'math'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-149',
    barcode: '005.1 DP',
    title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
    authorOrBrand: 'Erich Gamma, Richard Helm (Gang of Four)',
    description: 'The classic Gang of Four reference: Creational, Structural, and Behavioral OOP design patterns.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-J4',
    tags: ['design-patterns', 'gof', 'oop'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-150',
    barcode: '005.1 REF',
    title: 'Refactoring: Improving the Design of Existing Code (2nd Ed)',
    authorOrBrand: 'Martin Fowler',
    description: 'Catalog of refactorings, code smells, testing techniques, and object-oriented architectural redesign.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134757599-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-J5',
    tags: ['refactoring', 'clean-code', 'fowler'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-151',
    barcode: '005.1 DDD',
    title: 'Domain-Driven Design: Tackling Complexity in Software',
    authorOrBrand: 'Eric Evans',
    description: 'Bounded contexts, ubiquitous language, aggregates, entities, value objects, and domain event architectures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321125217-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-K1',
    tags: ['ddd', 'architecture', 'domain-modeling'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-152',
    barcode: '005.1 ARCH',
    title: 'Clean Architecture: A Craftsman\'s Guide to Software Structure',
    authorOrBrand: 'Robert C. Martin (Uncle Bob)',
    description: 'Solid design principles, component boundaries, dependency inversion, entity rules, and decoupled framework architectures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134494166-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-K2',
    tags: ['clean-architecture', 'solid-principles', 'software-design'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-153',
    barcode: '006.310 NLP2',
    title: 'Natural Language Processing with Transformers',
    authorOrBrand: 'Lewis Tunstall, Leandro von Werra',
    description: 'Hugging Face Transformers library: BERT, GPT, T5, fine-tuning sequence classification, text generation, and RAG pipelines.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781098103248-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-K3',
    tags: ['nlp', 'transformers', 'huggingface'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-154',
    barcode: '006.310 GNN2',
    title: 'Graph Representation Learning',
    authorOrBrand: 'William L. Hamilton',
    description: 'Graph Neural Networks (GNNs), node embeddings, GraphSAGE, Graph Attention Networks (GAT), and link prediction algorithms.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781681739632-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-K4',
    tags: ['gnn', 'graph-learning', 'ai'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-155',
    barcode: '005.133 TS2',
    title: 'Programming TypeScript',
    authorOrBrand: 'Boris Cherny',
    description: 'Advanced type system: generic constraints, mapped types, conditional types, algebraic data types, and strict compiler configurations.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491999837-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-K5',
    tags: ['typescript', 'javascript', 'type-system'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-156',
    barcode: '005.276 REACT2',
    title: 'Learning React (2nd Edition)',
    authorOrBrand: 'Alex Banks & Eve Porcello',
    description: 'Modern React 18: functional components, custom hooks, context state management, server components, and performance optimization.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492051725-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-L1',
    tags: ['react', 'frontend', 'javascript'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-157',
    barcode: '005.1 SRE',
    title: 'Site Reliability Engineering: How Google Runs Production Systems',
    authorOrBrand: 'Betsy Beyer, Chris Jones',
    description: 'SLOs, SLIs, error budgets, monitoring, incident management, automation, postmortems, and distributed system reliability.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491929124-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-L2',
    tags: ['sre', 'devops', 'google'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-158',
    barcode: '005.1 BPO',
    title: 'Building Microservices (2nd Edition)',
    authorOrBrand: 'Sam Newman',
    description: 'Microservice decomposition, API gateways, service mesh, saga transactions, distributed logging, and continuous deployment.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492034025-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-L3',
    tags: ['microservices', 'architecture', 'distributed-systems'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-159',
    barcode: '004.220 ARM',
    title: 'ARM Assembly Language: Fundamentals and Techniques (2nd Ed)',
    authorOrBrand: 'William Hohl & Christopher Hinds',
    description: 'Assembly language programming, Cortex-M architectures, memory maps, floating point unit operations, and interrupt handlers.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781482229851-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'SHELF-L4',
    tags: ['assembly', 'arm', 'embedded-systems'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-160',
    barcode: '005.133 KOTLIN',
    title: 'Kotlin in Action',
    authorOrBrand: 'Dmitry Jemerov & Svetlana Isakova',
    description: 'Null safety, extension functions, coroutines, higher-order functions, delegates, and Android app architecture.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781617293290-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-L5',
    tags: ['kotlin', 'android', 'jvm'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  }
];

export function findCatalogItemById(id: string): ResourceDTO | undefined {
  return FALLBACK_CATALOG.find((item) => item.id === id || item.barcode === id);
}
