import { ResourceDTO } from '@/lib/types';

export const FALLBACK_CATALOG: ResourceDTO[] = [
  {
    id: 'res-101',
    barcode: '005.133 LIB',
    title: 'Designing Data-Intensive Applications',
    authorOrBrand: 'Martin Kleppmann',
    description: 'The definitive guide to distributed systems, storage engines, consensus protocols, and stream processing architectures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-A1',
    tags: ['programming', 'distributed-systems', 'architecture'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-102',
    barcode: '005.741 MON',
    title: 'MongoDB: The Definitive Guide (3rd Ed)',
    authorOrBrand: 'Shannon Bradshaw & Eoin Brazil',
    description: 'Comprehensive guide to document data modeling, aggregation pipelines, replica sets, and sharded cluster management.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491954249-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 0,
    location: 'SHELF-A2',
    tags: ['database', 'nosql', 'mongodb'],
    status: 'BORROWED',
    activeQueueCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-103',
    barcode: '005.276 SPR',
    title: 'Spring Boot 3 in Action',
    authorOrBrand: 'Craig Walls',
    description: 'Building microservices, Spring Security JWT authentication, WebFlux reactive streams, and REST API controllers.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781617292545-L.jpg',
    type: 'BOOK',
    totalQuantity: 3,
    availableQuantity: 1,
    location: 'SHELF-A3',
    tags: ['java', 'spring-boot', 'backend'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-104',
    barcode: '621.381 OSC',
    title: 'Rigol DS1054Z 50MHz Digital Storage Oscilloscope',
    authorOrBrand: 'Rigol Technologies',
    description: '4-channel digital oscilloscope with 1GSa/s sampling rate, 12Mpts memory depth, and SPI/I2C protocol decoder module.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 2,
    availableQuantity: 2,
    location: 'LAB-ROOM-204',
    tags: ['hardware', 'electronics', 'oscilloscope'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-105',
    barcode: '621.395 FPGA',
    title: 'Xilinx Artix-7 FPGA Nexys A7 Trainer Kit',
    authorOrBrand: 'Digilent / Xilinx',
    description: 'FPGA development board with 101,440 logic cells, 240 DSP slices, 15.8 Mb BRAM, PMOD expanders, and VGA output.',
    coverImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 3,
    availableQuantity: 0,
    location: 'LAB-ROOM-204',
    tags: ['lab-kit', 'fpga', 'verilog'],
    status: 'BORROWED',
    activeQueueCount: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-106',
    barcode: '371.330 SEM',
    title: 'Capstone Seminar Room 402B (8-Person Capacity)',
    authorOrBrand: 'Campus Library Facilities',
    description: 'Acoustically dampened seminar room equipped with 4K interactive touchscreen display, dual whiteboards, and HDMI presentation hub.',
    coverImageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80',
    type: 'SEMINAR_ROOM',
    totalQuantity: 1,
    availableQuantity: 1,
    location: 'FLOOR-4',
    tags: ['seminar-room', 'collaboration', 'study'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-107',
    barcode: '005.117 CLN',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    authorOrBrand: 'Robert C. Martin (Uncle Bob)',
    description: 'Principles, patterns, and practices of writing clean, readable, refactorable, and maintainable software code.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-B1',
    tags: ['clean-code', 'refactoring', 'agile'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-108',
    barcode: '005.300 SYS',
    title: 'System Design Interview — An Insider\'s Guide',
    authorOrBrand: 'Alex Xu',
    description: 'Step-by-step framework for designing large-scale web systems: rate limiters, key-value stores, distributed caches, and newsfeed algorithms.',
    coverImageUrl: 'https://images-na.ssl-images-amazon.com/images/I/71u9i8S2GGL.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 1,
    location: 'SHELF-B2',
    tags: ['system-design', 'interview', 'scalability'],
    status: 'AVAILABLE',
    activeQueueCount: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-109',
    barcode: '005.100 ALG',
    title: 'Introduction to Algorithms (CLRS 4th Edition)',
    authorOrBrand: 'Thomas H. Cormen, Charles E. Leiserson',
    description: 'The standard algorithm textbook covering dynamic programming, graph algorithms, NP-completeness, and B-trees.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262046305-L.jpg',
    type: 'BOOK',
    totalQuantity: 8,
    availableQuantity: 5,
    location: 'SHELF-B3',
    tags: ['algorithms', 'data-structures', 'cs-theory'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-110',
    barcode: '004.600 NET',
    title: 'Computer Networking: A Top-Down Approach (8th Ed)',
    authorOrBrand: 'James Kurose & Keith Ross',
    description: 'Top-down layer approach to computer networks: HTTP/3, TCP/UDP sockets, BGP routing protocols, and Wi-Fi security.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780133594140-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 2,
    location: 'SHELF-C1',
    tags: ['networking', 'protocols', 'tcp-ip'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-111',
    barcode: '006.300 ART',
    title: 'Artificial Intelligence: A Modern Approach (4th Ed)',
    authorOrBrand: 'Stuart Russell & Peter Norvig',
    description: 'The leading textbook in AI covering probabilistic reasoning, search algorithms, reinforcement learning, and NLP.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134610993-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 0,
    location: 'SHELF-C2',
    tags: ['ai', 'machine-learning', 'python'],
    status: 'BORROWED',
    activeQueueCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-112',
    barcode: '006.310 DEE',
    title: 'Deep Learning (Adaptive Computation & ML Series)',
    authorOrBrand: 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
    description: 'Mathematical foundation of deep neural networks, backpropagation, CNNs, Transformers, and Generative Adversarial Networks.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262035613-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-C3',
    tags: ['deep-learning', 'neural-networks', 'pytorch'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-113',
    barcode: '621.398 RPI',
    title: 'Raspberry Pi 5 (8GB) Edge Computing Starter Kit',
    authorOrBrand: 'Raspberry Pi Foundation',
    description: 'Quad-core ARM Cortex-A76 board with active cooler, NVMe M.2 HAT, 64GB microSD, and camera module for IoT edge AI.',
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'LAB-ROOM-204',
    tags: ['hardware', 'raspberry-pi', 'iot', 'edge-ai'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-114',
    barcode: '621.399 ARD',
    title: 'Arduino Mega 2560 Sensor & Mechatronics Kit',
    authorOrBrand: 'Arduino Official',
    description: 'ATmega2560 board with 54 digital I/O pins, 16 analog inputs, stepper motor drivers, ultrasonic sensors, and LCD shield.',
    coverImageUrl: 'https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 5,
    availableQuantity: 4,
    location: 'LAB-ROOM-204',
    tags: ['lab-kit', 'arduino', 'mechatronics'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-115',
    barcode: '621.382 DMM',
    title: 'Keysight 34461A 6½ Digit Precision Multimeter',
    authorOrBrand: 'Keysight Technologies',
    description: 'Truevolt benchtop digital multimeter with 0.0035% DC accuracy, LAN/USB connectivity, and trend chart graphing display.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 2,
    availableQuantity: 1,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'multimeter', 'precision'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-116',
    barcode: '371.331 ROB',
    title: 'Robotics Lab Project Pod 104 (12-Person Capacity)',
    authorOrBrand: 'Campus Engineering Facilities',
    description: 'High-clearance robotics development bay equipped with overhead power drop cords, soldering station, 3D printer, and Ethernet drops.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    type: 'SEMINAR_ROOM',
    totalQuantity: 1,
    availableQuantity: 1,
    location: 'BUILDING-4',
    tags: ['seminar-room', 'robotics', 'workshop'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-117',
    barcode: '005.131 CSAPP',
    title: "Computer Systems: A Programmer's Perspective",
    authorOrBrand: 'Randal E. Bryant & David R. O\'Hallaron',
    description: 'Machine-level code execution, processor architecture, virtual memory, dynamic memory allocation, and concurrent programming.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134092669-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 5,
    location: 'SHELF-D1',
    tags: ['cs-systems', 'c-programming', 'memory'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-118',
    barcode: '006.312 PDS',
    title: 'Python Data Science Handbook (2nd Ed)',
    authorOrBrand: 'Jake VanderPlas',
    description: 'Essential tools for working with data in Python: IPython, NumPy, Pandas, Matplotlib, and Scikit-Learn pipelines.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781098115784-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-D2',
    tags: ['python', 'data-science', 'pandas'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-119',
    barcode: '621.388 LOG',
    title: 'Saleae Logic Pro 16 USB Logic Analyzer Kit',
    authorOrBrand: 'Saleae Inc',
    description: '16-channel high-speed logic analyzer with 500MS/s digital sampling, analog recording, and SPI/I2C/CAN bus decoding.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 3,
    availableQuantity: 2,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'logic-analyzer', 'electronics'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-120',
    barcode: '006.800 VR',
    title: 'Meta Quest 3 Spatial Computing & VR Dev Kit',
    authorOrBrand: 'Meta Reality Labs',
    description: 'Mixed-reality spatial computing head-mounted display with dual RGB pass-through cameras, Snapdragon XR2 Gen 2, and Unity/Unreal SDKs.',
    coverImageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 2,
    availableQuantity: 1,
    location: 'LAB-ROOM-301',
    tags: ['lab-kit', 'vr', 'spatial-computing', 'unity'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-121',
    barcode: '005.430 OS',
    title: 'Operating System Concepts (10th Edition)',
    authorOrBrand: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
    description: 'Process synchronization, virtual memory management, file systems, I/O subsystems, virtual machines, and security protection.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781118063330-L.jpg',
    type: 'BOOK',
    totalQuantity: 8,
    availableQuantity: 4,
    location: 'SHELF-D3',
    tags: ['operating-systems', 'kernel', 'memory'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-122',
    barcode: '005.453 CMP',
    title: 'Compilers: Principles, Techniques, and Tools (Dragon Book)',
    authorOrBrand: 'Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman',
    description: 'Lexical analysis, syntax-directed translation, intermediate code generation, run-time environments, and code optimization.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321486813-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-E1',
    tags: ['compilers', 'parsing', 'optimization'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-123',
    barcode: '005.740 SQL',
    title: 'High Performance MySQL (4th Edition)',
    authorOrBrand: 'Silvia Botros & Jeremy Tinley',
    description: 'Optimization, backups, replication, scaling, indexing, InnoDB engine internals, and query execution profiling.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492080519-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-E2',
    tags: ['database', 'mysql', 'sql-tuning'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-124',
    barcode: '006.310 PRML',
    title: 'Pattern Recognition and Machine Learning',
    authorOrBrand: 'Christopher M. Bishop',
    description: 'Comprehensive introduction to Bayesian methods, linear classification, neural networks, kernel methods, and graphical models.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780387310732-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 3,
    location: 'SHELF-E3',
    tags: ['machine-learning', 'statistics', 'bayesian'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-125',
    barcode: '005.133 CPP',
    title: 'The C++ Programming Language (4th Edition)',
    authorOrBrand: 'Bjarne Stroustrup',
    description: 'Definitive resource on C++11 core language features, standard library containers, move semantics, and generic programming.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321563842-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 5,
    location: 'SHELF-F1',
    tags: ['cpp', 'programming', 'stl'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-126',
    barcode: '005.133 RUST',
    title: 'The Rust Programming Language',
    authorOrBrand: 'Steve Klabnik & Carol Nichols',
    description: 'Memory safety without garbage collection: ownership, borrowing, lifetimes, cargo package manager, and concurrency.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781593278281-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-F2',
    tags: ['rust', 'systems-programming', 'memory-safety'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-127',
    barcode: '005.754 RED',
    title: 'Redis in Action',
    authorOrBrand: 'Josiah L. Carlson',
    description: 'In-memory data structure store: key-value caching, Pub/Sub messaging, geospatial indexes, Lua scripting, and Sentinel cluster HA.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781617290855-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-F3',
    tags: ['redis', 'caching', 'nosql'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-128',
    barcode: '004.620 KAF',
    title: 'Kafka: The Definitive Guide (2nd Edition)',
    authorOrBrand: 'Gwen Shapira, Todd Palino, Rajini Sivaram',
    description: 'Distributed event streaming platform: partition architecture, consumer groups, Kafka Connect, Schema Registry, and Exactly-Once Semantics.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492043089-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 3,
    location: 'SHELF-G1',
    tags: ['kafka', 'event-streaming', 'distributed-systems'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-129',
    barcode: '005.800 SEC',
    title: "The Web Application Hacker's Handbook (2nd Ed)",
    authorOrBrand: 'Dafydd Stuttard & Marcus Pinto',
    description: 'Attacking and defending web applications: SQL injection, XSS, CSRF, authentication bypass, session hijacking, and API security.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781118026472-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 2,
    location: 'SHELF-G2',
    tags: ['cybersecurity', 'web-security', 'pentesting'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-130',
    barcode: '006.370 CV',
    title: 'Computer Vision: Algorithms and Applications',
    authorOrBrand: 'Richard Szeliski',
    description: 'Image formation, feature detection, motion estimation, structure from motion, 3D reconstruction, and deep learning vision models.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781848829343-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-G3',
    tags: ['computer-vision', 'opencv', 'image-processing'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-131',
    barcode: '006.380 RL',
    title: 'Reinforcement Learning: An Introduction (2nd Ed)',
    authorOrBrand: 'Richard S. Sutton & Andrew G. Barto',
    description: 'Markov decision processes, dynamic programming, Monte Carlo methods, Temporal-Difference learning, Q-learning, and policy gradients.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780262039246-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-H1',
    tags: ['reinforcement-learning', 'ai', 'q-learning'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-132',
    barcode: '005.140 TST',
    title: 'Test Driven Development: By Example',
    authorOrBrand: 'Kent Beck',
    description: 'Red-Green-Refactor workflow, writing clean automated unit tests, mock objects, and test-driven architecture design patterns.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780321146533-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-H2',
    tags: ['tdd', 'testing', 'software-engineering'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-133',
    barcode: '005.730 DS',
    title: 'Data Structures and Algorithm Analysis in C++',
    authorOrBrand: 'Mark Allen Weiss',
    description: 'AVL trees, Splay trees, Priority Queues (Heaps), Disjoint Set data structure, Graph algorithms (Dijkstra, Kruskal), and amortized analysis.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780132847377-L.jpg',
    type: 'BOOK',
    totalQuantity: 7,
    availableQuantity: 4,
    location: 'SHELF-H3',
    tags: ['data-structures', 'algorithms', 'cpp'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-134',
    barcode: '004.350 PAR',
    title: 'An Introduction to Parallel Programming',
    authorOrBrand: 'Peter Pacheco',
    description: 'MPI (Message Passing Interface), Pthreads, OpenMP multi-threading, GPU parallel computing, and performance scalability tuning.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780123742605-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-I1',
    tags: ['parallel-computing', 'mpi', 'openmp'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-135',
    barcode: '005.300 K8S',
    title: 'Kubernetes Up & Running (3rd Edition)',
    authorOrBrand: 'Brendan Burns, Joe Beda, Kelsey Hightower',
    description: 'Container orchestration: Pods, Services, Ingress controllers, ConfigMaps, Secrets, Horizontal Pod Autoscaling, and Helm charts.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781098110208-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-I2',
    tags: ['kubernetes', 'devops', 'docker'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-136',
    barcode: '005.133 GO',
    title: 'The Go Programming Language',
    authorOrBrand: 'Alan A. A. Donovan & Brian W. Kernighan',
    description: 'Goroutines, channels, interfaces, reflection, low-level unsafe pointer operations, and building concurrent cloud services in Go.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780134190440-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-I3',
    tags: ['golang', 'concurrency', 'cloud-native'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-137',
    barcode: '005.133 PY',
    title: 'Fluent Python (2nd Edition)',
    authorOrBrand: 'Luciano Ramalho',
    description: 'Pythonic data models, generator functions, coroutines, asyncio event loops, type hinting, decorators, and meta-programming.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491946008-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-J1',
    tags: ['python', 'advanced-python', 'asyncio'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-138',
    barcode: '006.310 PYT',
    title: 'Programming PyTorch for Deep Learning',
    authorOrBrand: 'Ian Pointer',
    description: 'Building, training, and deploying neural networks: CNNs, Transfer Learning, Recurrent Networks, TensorBoard, and PyTorch Lightning.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492045359-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 2,
    location: 'SHELF-J2',
    tags: ['pytorch', 'deep-learning', 'ai'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-139',
    barcode: '005.741 CAS',
    title: 'Cassandra: The Definitive Guide (3rd Edition)',
    authorOrBrand: 'Jeff Carpenter & Eben Hewitt',
    description: 'Distributed NoSQL database: peer-to-peer architecture, tuneable consistency levels, CQL, SSTables, and cross-datacenter replication.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492055624-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-J3',
    tags: ['cassandra', 'nosql', 'distributed-database'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-140',
    barcode: '004.220 ARCH',
    title: 'Computer Architecture: A Quantitative Approach (6th Ed)',
    authorOrBrand: 'John L. Hennessy & David A. Patterson',
    description: 'Instruction-level parallelism, speculative execution, cache hierarchies, domain-specific accelerators, and GPU SIMD architectures.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780128119051-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-K1',
    tags: ['computer-architecture', 'hardware', 'processors'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },

  // 141 - 150: HARDWARE & LAB KITS
  {
    id: 'res-141',
    barcode: '621.381 FUN',
    title: 'Siglent SDG1032X 30MHz Function Generator',
    authorOrBrand: 'Siglent Technologies',
    description: 'Dual-channel arbitrary waveform generator with 150MSa/s sampling rate, 14-bit vertical resolution, and sweep burst functions.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 3,
    availableQuantity: 2,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'signal-generator', 'electronics'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-142',
    barcode: '621.398 ESP',
    title: 'ESP32-WROOM-32D Dual-Core Wi-Fi & Bluetooth IoT Kit',
    authorOrBrand: 'Espressif Systems',
    description: 'Dual-core 240MHz microcontroller with integrated Wi-Fi, BLE, capacitive touch sensors, Hall sensors, and FreeRTOS support.',
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 8,
    availableQuantity: 6,
    location: 'LAB-ROOM-204',
    tags: ['lab-kit', 'esp32', 'iot', 'freertos'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-143',
    barcode: '621.399 STM',
    title: 'STM32F407G-DISC1 ARM Cortex-M4 Discovery Kit',
    authorOrBrand: 'STMicroelectronics',
    description: 'ARM Cortex-M4 168MHz MCU with FPU, ST-LINK/V2-1 debugger, MEMS motion sensor, digital microphone, and audio DAC.',
    coverImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'LAB-ROOM-204',
    tags: ['lab-kit', 'stm32', 'arm', 'embedded'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-144',
    barcode: '621.382 PWR',
    title: 'Korad KA3005D Programmable DC Power Supply (30V 5A)',
    authorOrBrand: 'Korad Technology',
    description: 'Precision regulated DC bench power supply with 10mV/1mA resolution, constant current/voltage modes, and OVP/OCP protection.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'power-supply', 'bench-equipment'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-145',
    barcode: '621.389 SLD',
    title: 'Weller WE1010NA Digital Soldering Station & ESD Safety Kit',
    authorOrBrand: 'Weller Soldering',
    description: '70W digital soldering station with temperature lock, automatic standby, ESD safe iron handle, and brass wire tip cleaner.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 5,
    availableQuantity: 4,
    location: 'LAB-ROOM-206',
    tags: ['lab-kit', 'soldering', 'workbench'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-146',
    barcode: '621.395 ANK',
    title: 'Anker 737 Power Bank 140W Portable Lab Charger',
    authorOrBrand: 'Anker Innovations',
    description: '24,000mAh portable power bank with USB Power Delivery 3.1 140W output, smart digital display, and multi-device charging.',
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 6,
    availableQuantity: 5,
    location: 'LAB-ROOM-204',
    tags: ['hardware', 'power-bank', 'lab-accessories'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-147',
    barcode: '621.381 PROB',
    title: 'Tektronix TPP0200 200MHz 10X Passive Probes (Set of 4)',
    authorOrBrand: 'Tektronix Instrumentation',
    description: '200MHz bandwidth passive voltage probes with 10X attenuation, 300V CAT II safety rating, and grounding alligator clips.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'probes', 'oscilloscope'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-148',
    barcode: '621.399 SENS',
    title: 'SunFounder 37-in-1 Sensor Modules Kit for Microcontrollers',
    authorOrBrand: 'SunFounder Education',
    description: 'Comprehensive sensor kit including ultrasonic distance, DHT11 temp/humidity, GY-521 gyro/accel, IR obstacle, and relay modules.',
    coverImageUrl: 'https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 6,
    availableQuantity: 5,
    location: 'LAB-ROOM-204',
    tags: ['lab-kit', 'sensors', 'electronics'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-149',
    barcode: '621.388 SMR',
    title: 'Hakko FA-400 Benchtop Smoke Absorber & Fume Extractor',
    authorOrBrand: 'Hakko Corporation',
    description: 'Compact ESD-safe benchtop soldering fume extractor with activated carbon filter for removing soldering smoke flux toxins.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 4,
    availableQuantity: 4,
    location: 'LAB-ROOM-206',
    tags: ['lab-kit', 'safety', 'soldering'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-150',
    barcode: '621.395 FLIR',
    title: 'FLIR E4 Compact Thermal Imaging Camera with MSX',
    authorOrBrand: 'FLIR Systems',
    description: '80x60 thermal infrared camera resolution with MSX image enhancement for inspecting PCB thermal hot spots and component shorts.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 2,
    availableQuantity: 1,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'thermal-camera', 'pcb-diagnostics'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },

  // 151 - 160: SEMINAR ROOMS & SPECIALIZED STUDY SPACES
  {
    id: 'res-151',
    barcode: '371.330 SEM1',
    title: 'Capstone Seminar Room 401A (6-Person Capacity)',
    authorOrBrand: 'Campus Facilities',
    description: 'Acoustic glass seminar room equipped with 55-inch 4K screen, HDMI input, whiteboards, and quiet study ventilation.',
    coverImageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80',
    type: 'SEMINAR_ROOM',
    totalQuantity: 1,
    availableQuantity: 1,
    location: 'BUILDING-3',
    tags: ['seminar-room', 'group-study'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-152',
    barcode: '371.330 SEM3',
    title: 'Capstone Seminar Room 403C (10-Person Capacity)',
    authorOrBrand: 'Campus Facilities',
    description: 'Large teamwork room with modular conference tables, dual whiteboards, 4K screen with wireless AirPlay/Miracast casting.',
    coverImageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=600&q=80',
    type: 'SEMINAR_ROOM',
    totalQuantity: 1,
    availableQuantity: 1,
    location: 'BUILDING-3',
    tags: ['seminar-room', 'presentation'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-153',
    barcode: '371.330 SEM4',
    title: 'AI Research Lab Conference Suite 501 (16-Person Capacity)',
    authorOrBrand: 'Engineering Faculty Facilities',
    description: 'High-tier conference room with dual laser projectors, surround audio, ceiling mic array, and video conferencing hub.',
    coverImageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80',
    type: 'SEMINAR_ROOM',
    totalQuantity: 1,
    availableQuantity: 1,
    location: 'BUILDING-5',
    tags: ['seminar-room', 'conference', 'faculty'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-154',
    barcode: '371.331 VR2',
    title: 'Spatial Computing VR Sandbox Pod 202 (8-Person Capacity)',
    authorOrBrand: 'Interactive Media Department',
    description: 'Padded floor VR testing bay equipped with ceiling lighthouse motion trackers, high-end GPU workstations, and spatial audio.',
    coverImageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=600&q=80',
    type: 'SEMINAR_ROOM',
    totalQuantity: 1,
    availableQuantity: 1,
    location: 'BUILDING-2',
    tags: ['seminar-room', 'vr-sandbox', 'media'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-155',
    barcode: '006.310 NLP',
    title: 'Natural Language Processing with Transformers',
    authorOrBrand: 'Lewis Tunstall, Leandro von Werra, Thomas Wolf',
    description: 'Hugging Face Transformers library: BERT, GPT, T5, fine-tuning sequence classification, text generation, and RAG pipelines.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781098103248-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-K2',
    tags: ['nlp', 'transformers', 'huggingface'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-156',
    barcode: '006.310 GNN',
    title: 'Graph Representation Learning',
    authorOrBrand: 'William L. Hamilton',
    description: 'Graph Neural Networks (GNNs), node embeddings, GraphSAGE, Graph Attention Networks (GAT), and link prediction algorithms.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781681739632-L.jpg',
    type: 'BOOK',
    totalQuantity: 4,
    availableQuantity: 2,
    location: 'SHELF-K3',
    tags: ['gnn', 'graph-learning', 'ai'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-157',
    barcode: '005.133 TS',
    title: 'Programming TypeScript',
    authorOrBrand: 'Boris Cherny',
    description: 'Advanced type system: generic constraints, mapped types, conditional types, algebraic data types, and strict compiler configurations.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781491999837-L.jpg',
    type: 'BOOK',
    totalQuantity: 6,
    availableQuantity: 4,
    location: 'SHELF-L1',
    tags: ['typescript', 'javascript', 'type-system'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-158',
    barcode: '005.276 REACT',
    title: 'Learning React (2nd Edition)',
    authorOrBrand: 'Alex Banks & Eve Porcello',
    description: 'Modern React 18: functional components, custom hooks, context state management, server components, and performance optimization.',
    coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781492051725-L.jpg',
    type: 'BOOK',
    totalQuantity: 5,
    availableQuantity: 3,
    location: 'SHELF-L2',
    tags: ['react', 'frontend', 'javascript'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-159',
    barcode: '621.398 CAN',
    title: 'PEAK PCAN-USB CAN Bus Adapter Kit for Automotive & Robotics',
    authorOrBrand: 'PEAK-System Technik',
    description: 'High-speed CAN bus 2.0A/B to USB interface adapter with galvanic isolation, DB9 connector, and PCAN-View monitoring software.',
    coverImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    type: 'HARDWARE',
    totalQuantity: 3,
    availableQuantity: 2,
    location: 'LAB-ROOM-205',
    tags: ['hardware', 'can-bus', 'robotics', 'automotive'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-160',
    barcode: '621.399 RTL',
    title: 'RTL-SDR Blog V4 Software Defined Radio Receiver Kit',
    authorOrBrand: 'RTL-SDR Blog',
    description: 'SMA software-defined radio receiver with 500kHz - 1.7GHz tuning range, TCXO 1PPM precision clock, and dipole antenna set.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    type: 'LAB_KIT',
    totalQuantity: 4,
    availableQuantity: 3,
    location: 'LAB-ROOM-204',
    tags: ['lab-kit', 'sdr', 'rf', 'wireless'],
    status: 'AVAILABLE',
    activeQueueCount: 0,
    createdAt: new Date().toISOString(),
  }
];

export function findCatalogItemById(id: string): ResourceDTO | undefined {
  return FALLBACK_CATALOG.find((item) => item.id === id || item.barcode === id);
}
